# Generated by Django 4.2.20 on 2025-04-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="Número do Processo"
                    ),
                ),
                ("cliente", models.CharField(max_length=100)),
                ("advogado_responsavel", models.CharField(max_length=100)),
                ("tipo_acao", models.CharField(max_length=100)),
                ("vara", models.CharField(max_length=100)),
                ("comarca", models.CharField(max_length=100)),
                ("data_inicio", models.DateField()),
                ("data_audiencia", models.DateField(blank=True, null=True)),
                ("data_sentenca", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("andamento", "Em andamento"),
                            ("concluido", "Concluído"),
                            ("suspenso", "Suspenso"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="andamento",
                        max_length=20,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
