# Generated by Django 4.2.20 on 2025-04-05 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0001_initial"),
        ("processos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processo",
            name="advogado_responsavel",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="atualizado_em",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="comarca",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="criado_em",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="data_audiencia",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="data_inicio",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="data_sentenca",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="tipo_acao",
        ),
        migrations.RemoveField(
            model_name="processo",
            name="vara",
        ),
        migrations.AddField(
            model_name="processo",
            name="data_abertura",
            field=models.DateTimeField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="processo",
            name="tipo",
            field=models.CharField(default=datetime.date(2024, 1, 1), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="processo",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="clientes.cliente"
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="numero",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name="processo",
            name="status",
            field=models.CharField(
                choices=[
                    ("andamento", "Em andamento"),
                    ("concluido", "Concluído"),
                    ("arquivado", "Arquivado"),
                ],
                max_length=50,
            ),
        ),
    ]
