# Generated by Django 4.2.20 on 2025-04-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("processos", "0002_remove_processo_advogado_responsavel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="documentos/")),
                ("descricao", models.CharField(blank=True, max_length=100)),
                ("data_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="processos.processo",
                    ),
                ),
            ],
        ),
    ]
